Repository jetstreamgg/marketing-page, pull requests merged in 2025-05, with the labels that each got.

#41 Update Crypto General tab faq data
  app/(main)/faq/faqData.ts
Labels: wip

#40 staging < development
  app/(main)/components/Features.tsx
  app/(main)/faq/components/FaqList.tsx
  app/(main)/faq/faqCryptoGeneral.ts
  app/(main)/faq/faqData.ts
  app/(main)/faq/faqNetworkIntegrations.ts
  app/(main)/faq/faqSkyEcosystem.ts
  app/(main)/faq/faqSkyLink.ts
  app/(main)/faq/faqSkySavingsRate.ts
  app/(main)/faq/faqSkyTokenRewards.ts
  app/(main)/faq/faqSkyTokens.ts
  app/(main)/faq/faqStakingEngine.ts
  app/(main)/faq/faqUpgradeAndTrade.ts
  app/(main)/features/components/cards/SkyLinkCard.tsx
  app/components/icons/Activation.tsx
  app/hooks/useRandomL2Name.ts
  public/features-skylink-mobile.png
  public/products_skybridge.png
Labels: Ready for Review

#43 staging > main
  app/(main)/components/FAQ.tsx
  app/(main)/components/Features.tsx
  app/(main)/faq/components/FaqList.tsx
  app/(main)/faq/faqCryptoGeneral.ts
  app/(main)/faq/faqData.ts
  app/(main)/faq/faqNetworkIntegrations.ts
  app/(main)/faq/faqSkyEcosystem.ts
  app/(main)/faq/faqSkyLink.ts
  app/(main)/faq/faqSkySavingsRate.ts
  app/(main)/faq/faqSkyTokenRewards.ts
  app/(main)/faq/faqSkyTokens.ts
  app/(main)/faq/faqStakingEngine.ts
  app/(main)/faq/faqUpgradeAndTrade.ts
  app/(main)/features/components/FeaturesHero.tsx
  app/(main)/features/components/FeaturesPageCard.tsx
  app/(main)/features/components/PrefetchFeaturesAssets.tsx
  app/(main)/features/components/cards/SealCard.tsx
  app/(main)/features/components/cards/SkyLinkCard.tsx
  app/(main)/features/components/cards/StakeCard.tsx
  app/(main)/features/components/cards/UpgradeCard.tsx
  app/(main)/features/featuresData.ts
  app/components/Banner.tsx
  app/components/Footer.tsx
  app/components/PopoverSealInfo.tsx
  app/components/SkyCard.tsx
  app/components/icons/Activation.tsx
  app/components/menu/DesktopMenu.tsx
  app/components/menu/sections.ts
  app/hooks/useRandomL2Name.ts
  public/features-skylink-mobile.png
  public/products_seal_1.png
  public/products_seal_1_mobile.png
  public/products_seal_2.png
  public/products_seal_2_mobile.png
  public/products_seal_3.png
  public/products_seal_3_mobile.png
  public/products_seal_4.png
  public/products_seal_4_mobile.png
  public/products_seal_5.png
  public/products_seal_5_mobile.png
  public/products_skybridge.png
  public/products_stake_1.png
  public/products_stake_1_mobile.png
  public/products_stake_2.png
  public/products_stake_2_mobile.png
  public/products_stake_3.png
  public/products_stake_3_mobile.png
  public/products_stake_4.png
  public/products_stake_4_mobile.png
  public/products_stake_5.png
  public/products_stake_5_mobile.png
  public/products_stake_6.png
  public/products_stake_6_mobile.png
Labels: release PR

#47 Fix Staking card navigation in features page
  app/(main)/features/components/cards/StakeCard.tsx
Labels: Ready for Review

#48 Remove alpha launch from staking feature
  app/(main)/features/featuresData.ts
Labels: Ready for Review

#49 staging > main
  app/(main)/features/components/cards/StakeCard.tsx
  app/(main)/features/featuresData.ts
Labels: Ready for Review
